---
- name: start service firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: disabled dhcpv6-client
  firewalld:
    zone: public
    service: dhcpv6-client
    state: disabled
    permanent: yes
    immediate: yes

- name: set ssh permit
  firewalld:
    zone: public
    rich_rule: 'rule family=ipv4 source address="{{ item }}" service name="ssh" accept'
    state: enabled
    permanent: yes                                                                                  
    immediate: yes
  with_items: "{{ ssh_ip }}"

- name: zabbix-agent port permit
  firewalld:
    zone: public
    port: 10050/tcp
    state: enabled
    permanent: yes
    immediate: yes
  when: "'server' in group_names"

- name: set postgresql permit
  firewalld:
    zone: public
    rich_rule: 'rule family=ipv4 source address="{{ item }}" service name="postgresql" accept'
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ ssh_ip }}"
